### ISSUE TITLE
Module breaks cellular functionality on the 7 Pro

### ISSUE THREAD

**Issue by snappyapple632** [Magisk-Modules-Repo/OOSNativeCallRecordingEnabler#13]
I am using a GM1917 on OOS 10.0.2. I would assume this is due to Android 10 being unsupported. I have tried rebooting twice after enabling the module with no luck.

**Comment by shadowstepxda** [comment]
Hi! It's been working fine for others on the OP 7 Pro. Try uninstalling the module, rebooting, reinstalling the module from scratch (from Magisk Manager's Download section). It should work.

Do note uninstalling is not the same as disabling, and you have to uninstall the module before updating OOS and then reinstall it again once you're done updating, to avoid issues.
