### ISSUE TITLE
Module breaks cellular on A10

### ISSUE THREAD

**Issue by Electric1447** [Magisk-Modules-Repo/OOSNativeCallRecordingEnabler#14]
The module makes the sim card not work on android 10

**Comment by njames93** [comment]
This happened to me when updating to 10, uninstall the module, reboot then reinstall.

**Comment by shadowstepxda** [comment]
Hi! It's been working fine for others on OOS 10. Try uninstalling the module, rebooting, reinstalling the module from scratch (from Magisk Manager's Download section). It should work.

Do note uninstalling is not the same as disabling, and you have to uninstall the module before updating OOS and then reinstall it again once you're done updating, to avoid issues.
