### ISSUE TITLE
Don't install it on 7 pro

### ISSUE THREAD

**Issue by sirandr3w** [Magisk-Modules-Repo/OOSNativeCallRecordingEnabler#15]
Don't install this on OP 7 pro android 10. This module make your first 4 CPU's cores running at max frequency all the time. My phone was on fire and at 30% battery with only 40mins of display usage and the problem was this module.

**Comment by shadowstepxda** [comment]
Hi! It's been working fine for others on the OP 7 Pro. Try uninstalling the module, rebooting, reinstalling the module from scratch (from Magisk Manager's Download section). It should work. Also, this module has no impact on battery life, it only modifies a system app.

Do note uninstalling is not the same as disabling, and you have to uninstall the module before updating OOS and then reinstall it again once you're done updating, to avoid issues.
