### ISSUE TITLE
Stop working on Oxygen OS 9.0.11 

### ISSUE THREAD

**Issue by rnabiullin** [Magisk-Modules-Repo/OOSNativeCallRecordingEnabler#16]
This module is stop working after update to OOS 9.0.11, as I think it's related by some changes in phone dialer, because in 9.0.10 was present 1 bug with it

**Comment by shadowstepxda** [comment]
Hi! It's been working fine for others on OOS 9.0.11 (myself included). Try uninstalling the module, rebooting, reinstalling the module from scratch (from Magisk Manager's Download section). It should work.

Do note uninstalling is not the same as disabling, and you have to uninstall the module before updating OOS and then reinstall it again once you're done updating, to avoid issues.
