### ISSUE TITLE
Failure to install

### ISSUE THREAD

**Issue by Shenron0** [Magisk-Modules-Repo/OOSNativeCallRecordingEnabler#17]
The module fails to install on the latest OOS Open Beta 13 with the latest canary release on the OnePlus 7

**Comment by shadowstepxda** [comment]
Magisk Canary broke one of the variables I was using. Has been fixed with [this](https://github.com/nipunnarang/oosnativecallrecordingenabler/commit/7b1ecac94de63a4b70ca6362aee73ac925bcde41) commit.
