### ISSUE TITLE
Oneplus9Pro EU 10.2.2

### ISSUE THREAD

**Issue by d1nd141** [Magisk-Modules-Repo/OOSNativeCallRecordingEnabler#19]
Hello,

worked fine under OPO7pro A11, but seems broken on OPO9pro.
Log attached
[magisk_install_log_2021-04-05T11_00_29Z.log](https://github.com/nipunnarang/oosnativecallrecordingenabler/files/6257307/magisk_install_log_2021-04-05T11_00_29Z.log)

**Comment by shadowstepxda** [comment]
Hi! I've had a look at the log, and I don't see any issue there. The module installation went through successfully. Unfortunately, I don't have the device with me to test, maybe OnePlus changed how call recording is enabled/disabled in the new versions of OOS. You can try one of the other methods listed in [this](https://forum.xda-developers.com/t/3634292/) thread of mine.
