### ISSUE TITLE
Doesn't work on OnePlus 6 Pie

### ISSUE THREAD

**Issue by eliaspizarro** [Magisk-Modules-Repo/OOSNativeCallRecordingEnabler#2]
Doesn't work on OnePlus 6 Pie and Magisk 17.1.

Note: if I run the following code from terminal, works

su -c 'settings put global op_voice_recording_supported_by_mcc 1'

**Comment by shadowstepxda** [comment]
> Doesn't work on OnePlus 6 Pie and Magisk 17.1.
> 
> Note: if I run the following code from terminal, works
> 
> su -c 'settings put global op_voice_recording_supported_by_mcc 1'

Hi! If you read through the last few pages of the support thread [here](https://forum.xda-developers.com/oneplus-5/themes/app-enable-call-recording-boot-t3634292), you'll see that OnePlus has made several changes over the last few OxygenOS releases which disable call recording after a while. I suggest you go through the first post as well as the thread that I linked to above to find other methods and workarounds which might work for you. Thanks!
