### ISSUE TITLE
Reboot disables the module

### ISSUE THREAD

**Issue by meminens** [Magisk-Modules-Repo/OOSNativeCallRecordingEnabler#4]
OnePlus 5T
Oxygen 5.1.7
Android 8.0.1
Stock ROM
Magisk 17.3
Magisk Manager 6.0.1

Call recording option disappears after every reboot. Reinstalling the module in Magisk and rebooting the device brings it back.

**Comment by meminens** [comment]
In addition, call recording option is disabled when a bluetooth headset is connected to the device. Is this per design?

**Comment by shadowstepxda** [comment]
In the recent versions of the OxygenOS, OnePlus added an activity that turned native call recording off if enabled manually by the user by any method. To alleviate this, I've just updated the module. Please check and see, call recording shouldn't getting disabled automatically now. Also, remember that it takes 30 seconds for the command to be executed by Magisk post the phone boot. So if you check for the option right after rebooting without waiting for at least more than 30 seconds (I recommend a minute), then the option won't be there.

**Comment by meminens** [comment]
Thanks!

**Comment by meminens** [comment]
@nipunnarang Problem persists after installing the latest version and rebooting. I waited 2 minutes before I opened the Phone app. Recording setting is not there. Any thoughts?
