### ISSUE TITLE
Call recording option dissapears after a day or two?

### ISSUE THREAD

**Issue by grasmanek94** [Magisk-Modules-Repo/OOSNativeCallRecordingEnabler#8]
Hey there, I have had this issue on the APK version so I had to manually launch the APK every so often. Was I delighted to see a Magisk module is available! I have version 7.0.0 installed of this module, what information would I need to provide for this issue to be debugged? It still happens with the module installed (APK installed too).

I have a OnePlus 5. OOS 5.1.5.

**Comment by shadowstepxda** [comment]
Hi! Sorry, just saw the issue that you created. I hope you've updated your OOS to the latest available version (OOS 9.x.x) and reinstalled the module -- it works fine. :)
